### ISSUE TITLE
Uncaught TypeError: Cannot read property 'focus' of undefined

### ISSUE THREAD

**Issue by amejia1** [amejia1/atom-xterm#15]
[Enter steps to reproduce:]

1. Add two terminal tabs to the bottom panel in such a way where they stay in the same "pane" in the bottom panel.
2. Restart Atom.

This seems harmless however since the terminals continue to work.

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [atom-xterm](https://github.com/amejia1/atom-xterm) package 3.0.0

### Stack Trace

Uncaught TypeError: Cannot read property 'focus' of undefined

```
At C:\Users\andre\.atom\packages\atom-xterm\lib\atom-xterm-element.js:293

TypeError: Cannot read property 'focus' of undefined
    at HTMLElement.focusOnTerminal (/packages/atom-xterm/lib/atom-xterm-element.js:342:26)
    at AtomXtermModel.focusOnTerminal (/packages/atom-xterm/lib/atom-xterm-model.js:224:26)
    at /packages/atom-xterm/lib/atom-xterm.js:287:22
    at Function.module.exports.Emitter.simpleDispatch (<embedded>:65891:20)
    at Emitter.module.exports.Emitter.emit (<embedded>:66007:34)
    at <embedded>:27976:30

```

### Commands

```
```

### Non-Core Packages

```
atom-ide-ui 0.7.1 
atom-xterm 3.0.0 
highlight-selected 0.13.1 
ide-clangd 0.1.2 
ide-cpp 0.0.3 
ide-json 0.1.0 
ide-python 0.4.0 
ide-typescript 0.7.2 
language-typescript-grammars-only 1.6.0 
minimap 4.29.7 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-selection 4.5.0 
```

**Comment by amejia1** [comment]
Fixed in v3.0.1.
