### ISSUE TITLE
Uncaught TypeError: Cannot set property '0' of undefined

### ISSUE THREAD

**Issue by amejia1** [amejia1/atom-xterm#4]
[Enter steps to reproduce:]

1. Open anything with less (for example, `env | sort | less`). Output must have more rows than what the current terminal supports.
2. Close less.
3. Resize the terminal so that it has less rows.
4. Open the same content again with less and try to scroll down. Issue is triggered here.

**Atom**: 1.19.7 x64
**Electron**: 1.6.9
**OS**: Ubuntu 17.04
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot set property '0' of undefined

```
At /home/andres/github/atom-xterm/node_modules/xterm/lib/InputHandler.js:58

TypeError: Cannot set property '0' of undefined
    at InputHandler.addChar (/home/andres/github/atom-xterm/node_modules/xterm/lib/InputHandler.js:58:75)
    at Parser.parse (/home/andres/github/atom-xterm/node_modules/xterm/lib/Parser.js:180:44)
    at Terminal.innerWrite (/home/andres/github/atom-xterm/node_modules/xterm/lib/xterm.js:825:33)
    at /home/andres/github/atom-xterm/node_modules/xterm/lib/xterm.js:810:18
```

### Commands

```
  2x -1:52 atom-xterm:open-split-down (div.line)
```

### Non-Core Packages

```
atom-xterm 1.0.3 
```

**Comment by amejia1** [comment]
This issue has me stumped. So far the best workaround I know of is to do this whenever a new terminal is opened or resized. Open anything with less, quit less, than open anything with less again.

Something else I noticed, when opening a terminal with a sufficiently large number of rows, the first time I use less, the top portion of rows is cut off at the top of the screen. Closing and reopening less fixes this.

**Comment by amejia1** [comment]
Another note, the 'less' command available when using Bash from Git for Windows seems unaffected by this.

**Comment by amejia1** [comment]
This issue no longer appear when I use xterm.js v3. Just got to wait until v3 is released.

**Comment by amejia1** [comment]
Moved to xterm.js v3, issue now fixed.
