### ISSUE TITLE
Uncaught Error: resizing must be done using positive cols and rows

### ISSUE THREAD

**Issue by naveenbuddhar** [amejia1/atom-xterm#44]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.28.0 x64
**Electron**: 2.0.3
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [atom-xterm](https://github.com/amejia1/atom-xterm) package 6.4.1

### Stack Trace

Uncaught Error: resizing must be done using positive cols and rows

```
At C:\Users\nkumar\.atom\packages\atom-xterm\node_modules\node-pty-prebuilt\lib\windowsTerminal.js:125

Error: resizing must be done using positive cols and rows
    at WindowsTerminal.resize (/packages/atom-xterm/node_modules/node-pty-prebuilt/lib/windowsTerminal.js:125:19)
    at HTMLElement.refitTerminal (/packages/atom-xterm/lib/atom-xterm-element.js:521:29)
    at /packages/atom-xterm/lib/atom-xterm-element.js:93:20
    at callListenerProxy (/packages/atom-xterm/node_modules/element-resize-detector/src/element-resize-detector.js:153:17)
    at utils.forEach (/packages/atom-xterm/node_modules/element-resize-detector/src/collection-utils.js:14:22)
    at onResizeCallback (/packages/atom-xterm/node_modules/element-resize-detector/src/element-resize-detector.js:152:13)
    at /packages/atom-xterm/node_modules/element-resize-detector/src/detection-strategy/scroll.js:517:21
    at utils.forEach (/packages/atom-xterm/node_modules/element-resize-detector/src/collection-utils.js:14:22)
    at notifyListenersIfNeeded (/packages/atom-xterm/node_modules/element-resize-detector/src/detection-strategy/scroll.js:516:17)
    at /packages/atom-xterm/node_modules/element-resize-detector/src/detection-strategy/scroll.js:484:25
    at Object.process (/packages/atom-xterm/node_modules/batch-processor/src/batch-processor.js:124:17)
    at processBatch (/packages/atom-xterm/node_modules/batch-processor/src/batch-processor.js:37:29)
```

### Commands

```
     -5:36.6.0 autocomplete-plus:activate (input.hidden-input)
     -5:35.3.0 autocomplete-plus:cancel (input.hidden-input)
     -5:21 atom-xterm:open-split-up (input.hidden-input)
     -5:13.3.0 atom-xterm:open-split-down (input.hidden-input)
     -1:42.8.0 atom-ide-terminal:new-terminal (div.title.icon.icon-terminal)
     -1:36.1.0 pane:close (div.title.icon.icon-terminal)
  2x -1:28.4.0 atom-xterm:open-split-down (input.hidden-input)
     -1:00.0 atom-xterm:reorganize (textarea.xterm-helper-textarea)
     -0:39.7.0 atom-xterm:reorganize-bottom (input.hidden-input)
```

### Non-Core Packages

```
atom-react-autocomplete 0.1.10 
atom-xterm 6.4.1 
file-icons 2.1.21 
highlight-selected 0.13.1 
language-babel 2.85.0 
language-graphql 0.10.1 
language-haskell 1.17.8 
language-ini 1.20.0 
language-kotlin 0.5.0 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-rust 0.4.12 
language-scala 1.1.9 
language-swift 0.5.0 
language-thrift 1.0.2 
nuclide 0.317.0 
nuclide-format-js 0.0.46 
react 0.18.0 
react-snippets 1.1.1 
set-syntax 0.4.0 
sort-lines 0.18.0 
tool-bar 1.1.7 
```

**Comment by UziTech** [comment]
I forked `atom-xterm`, updated everything along with other fixes, and released it as [`x-terminal`](https://atom.io/packages/x-terminal) since `atom-xterm` doesn't seem to be maintained
