### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by johnmangino** [amejia1/atom-xterm#6]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.7 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.5
**Thrown From**: [atom-xterm](https://github.com/amejia1/atom-xterm) package 1.0.15

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Users/jmango/.atom/packages/atom-xterm/node_modules/xterm/lib/utils/BufferLine.js:11

TypeError: Cannot read property 'length' of undefined
    at Object.translateBufferLineToString (/packages/atom-xterm/node_modules/xterm/lib/utils/BufferLine.js:11:29)
    at /packages/atom-xterm/node_modules/xterm/lib/SelectionManager.js:96:38)
    at Object.rightClickHandler (/packages/atom-xterm/node_modules/xterm/lib/handlers/Clipboard.js:64:38)
    at /packages/atom-xterm/node_modules/xterm/lib/xterm.js:335:25)
```

### Commands

```
     -0:09.1.0 core:paste (textarea.xterm-helper-textarea)
     -0:05.5.0 atom-xterm:paste (span.)
```

### Non-Core Packages

```
atom-xterm 1.0.15 
autocomplete-python 1.10.1 
busy-signal 1.4.1 
intentions 1.1.2 
linter 2.1.4 
linter-flake8 2.2.1 
linter-ui-default 1.6.0 
python-debugger 0.2.0 
python-indent 1.1.0 
script 3.15.0 
```

**Comment by amejia1** [comment]
This problem is related to https://github.com/sourcelair/xterm.js/issues/661 . Using xterm.js v3 would fix this, but v3 is yet to be released.

**Comment by amejia1** [comment]
Moved to xterm.js v3, issue now fixed.
