### ISSUE TITLE
Uncaught RangeError: Invalid typed array length: Infinity

### ISSUE THREAD

**Issue by giteub13** [amejia1/atom-xterm#66]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.33.0 x64
**Electron**: 2.0.11
**OS**: Ubuntu 18.04.1
**Thrown From**: [atom-xterm](https://github.com/amejia1/atom-xterm) package 6.5.0

### Stack Trace

Uncaught RangeError: Invalid typed array length: Infinity

```
At /home/desmarets/.atom/packages/atom-xterm/node_modules/xterm/lib/BufferLine.js:176

RangeError: Invalid typed array length: Infinity
    at typedArrayConstructByLength (<anonymous>)
    at new Uint32Array (native)
    at BufferLine.resize (/packages/atom-xterm/node_modules/xterm/lib/BufferLine.js:176:24)
    at Buffer.resize (/packages/atom-xterm/node_modules/xterm/lib/Buffer.js:120:39)
    at BufferSet.resize (/packages/atom-xterm/node_modules/xterm/lib/BufferSet.js:78:22)
    at Terminal.resize (/packages/atom-xterm/node_modules/xterm/lib/Terminal.js:1103:22)
    at Terminal.resize (/packages/atom-xterm/node_modules/xterm/lib/public/Terminal.js:53:20)
    at HTMLElement.refitTerminal (/packages/atom-xterm/lib/atom-xterm-element.js:514:25)
    at HTMLElement.applyPendingTerminalProfileOptions (/packages/atom-xterm/lib/atom-xterm-element.js:489:12)
    at IntersectionObserver._this.terminalDivIntersectionObserver.IntersectionObserver.root (/packages/atom-xterm/lib/atom-xterm-element.js:102:20)
```

### Commands

```
```

### Non-Core Packages

```
atom-xterm 6.5.0 
file-icons 2.1.26 
gpp-compiler 3.0.7 
```

**Comment by UziTech** [comment]
I forked `atom-xterm`, updated everything along with other fixes, and released it as [`x-terminal`](https://atom.io/packages/x-terminal) since `atom-xterm` doesn't seem to be maintained
