### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by yuber83** [amejia1/atom-xterm#67]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Debian GNU/Linux
**Thrown From**: [atom-xterm](https://github.com/amejia1/atom-xterm) package 6.5.0

### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At /home/yvasquez/.atom/packages/atom-xterm/node_modules/xterm/lib/Linkifier.js:140

TypeError: Cannot read property '0' of undefined
    at Linkifier._doLinkifyRow (/packages/atom-xterm/node_modules/xterm/lib/Linkifier.js:140:24)
    at Linkifier._doLinkifyRow (/packages/atom-xterm/node_modules/xterm/lib/Linkifier.js:158:18)
    at Linkifier._doLinkifyRow (/packages/atom-xterm/node_modules/xterm/lib/Linkifier.js:158:18)
    at Linkifier._linkifyRow (/packages/atom-xterm/node_modules/xterm/lib/Linkifier.js:126:18)
    at Linkifier._linkifyRows (/packages/atom-xterm/node_modules/xterm/lib/Linkifier.js:54:18)
    at /packages/atom-xterm/node_modules/xterm/lib/Linkifier.js:49:69
```

### Commands

```
```

### Non-Core Packages

```
atom-react-autocomplete 0.1.10 
atom-react-native-style 0.2.0 
atom-xterm 6.5.0 
busy-signal 2.0.0 
intentions 1.1.5 
linter 2.3.0 
linter-ui-default 1.7.1 
prettier-atom 0.56.2 
react 0.18.0 
react-native-components 0.1.1 
react-redux-snippets 0.1.6 
vim-mode-plus 1.36.0 
```

**Comment by UziTech** [comment]
I forked `atom-xterm`, updated everything along with other fixes, and released it as [`x-terminal`](https://atom.io/packages/x-terminal) since `atom-xterm` doesn't seem to be maintained
