### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replaceCells' of undefined

### ISSUE THREAD

**Issue by itz-azhar** [amejia1/atom-xterm#68]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Mac OS X 10.14.1
**Thrown From**: [atom-xterm](https://github.com/amejia1/atom-xterm) package 6.5.0

### Stack Trace

Uncaught TypeError: Cannot read property 'replaceCells' of undefined

```
At /Users/mohd.azharkhan/.atom/packages/atom-xterm/node_modules/xterm/lib/InputHandler.js:435

TypeError: Cannot read property 'replaceCells' of undefined
    at InputHandler._eraseInBufferLine (/packages/atom-xterm/node_modules/xterm/lib/InputHandler.js:435:14)
    at InputHandler.eraseInDisplay (/packages/atom-xterm/node_modules/xterm/lib/InputHandler.js:449:22)
    at /packages/atom-xterm/node_modules/xterm/lib/InputHandler.js:95:84)
    at EscapeSequenceParser.parse (/packages/atom-xterm/node_modules/xterm/lib/EscapeSequenceParser.js:402:40)
    at InputHandler.parse (/packages/atom-xterm/node_modules/xterm/lib/InputHandler.js:191:22)
    at Terminal._innerWrite (/packages/atom-xterm/node_modules/xterm/lib/Terminal.js:893:32)
    at /packages/atom-xterm/node_modules/xterm/lib/Terminal.js:875:23
```

### Commands

```
     -2:26.2.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
  3x -2:23.7.0 core:move-right (input.hidden-input)
     -2:21.1.0 core:backspace (input.hidden-input)
     -2:20.9.0 core:move-right (input.hidden-input)
     -2:20.6.0 editor:newline (input.hidden-input)
     -2:17.2.0 core:move-right (input.hidden-input)
     -2:15.1.0 autocomplete-plus:confirm (input.hidden-input)
     -2:15.1.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
  3x -2:13.2.0 core:move-right (input.hidden-input)
     -2:10 core:move-left (input.hidden-input)
     -2:05.2.0 core:backspace (input.hidden-input)
     -2:03.5.0 core:save (input.hidden-input)
  3x -0:51.4.0 core:copy (input.hidden-input)
  2x -0:47.2.0 editor:newline (input.hidden-input)
     -0:45.5.0 core:paste (input.hidden-input)
     -0:35.5.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-code-syntax 0.3.1 
atom-code-ui 0.4.4 
atom-inline-blame 0.0.6 
atom-xterm 6.5.0 
autocomplete-python 1.12.0 
busy-signal 2.0.0 
emmet 2.4.3 
file-icons 2.1.29 
intentions 1.1.5 
language-generic-config 1.4.0 
language-ini 1.20.0 
linter 2.3.0 
linter-eslint 8.5.2 
linter-pycodestyle 2.1.3 
linter-ui-default 1.7.1 
minimap 4.29.9 
react 0.18.0 
```

**Comment by UziTech** [comment]
I forked `atom-xterm`, updated everything along with other fixes, and released it as [`x-terminal`](https://atom.io/packages/x-terminal) since `atom-xterm` doesn't seem to be maintained
