### ISSUE TITLE
Uncaught TypeError: Cannot read property '_data' of undefined

### ISSUE THREAD

**Issue by aradxc56** [amejia1/atom-xterm#70]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.35.1 x64
**Electron**: 2.0.18
**OS**: elementary OS
**Thrown From**: [atom-xterm](https://github.com/amejia1/atom-xterm) package 6.5.0

### Stack Trace

Uncaught TypeError: Cannot read property '_data' of undefined

```
At /home/ara/.atom/packages/atom-xterm/node_modules/xterm/lib/BufferLine.js:165

TypeError: Cannot read property '_data' of undefined
    at BufferLine.copyCellsFrom (/packages/atom-xterm/node_modules/xterm/lib/BufferLine.js:165:27)
    at Buffer._reflowSmaller (/packages/atom-xterm/node_modules/xterm/lib/Buffer.js:257:45)
    at Buffer._reflow (/packages/atom-xterm/node_modules/xterm/lib/Buffer.js:177:18)
    at Buffer.resize (/packages/atom-xterm/node_modules/xterm/lib/Buffer.js:152:18)
    at BufferSet.resize (/packages/atom-xterm/node_modules/xterm/lib/BufferSet.js:78:22)
    at Terminal.resize (/packages/atom-xterm/node_modules/xterm/lib/Terminal.js:1108:22)
    at Terminal.resize (/packages/atom-xterm/node_modules/xterm/lib/public/Terminal.js:53:20)
    at HTMLElement.refitTerminal (/packages/atom-xterm/lib/atom-xterm-element.js:514:25)
    at HTMLElement.applyPendingTerminalProfileOptions (/packages/atom-xterm/lib/atom-xterm-element.js:489:12)
    at IntersectionObserver._this.terminalDivIntersectionObserver.IntersectionObserver.root (/packages/atom-xterm/lib/atom-xterm-element.js:102:20)
```

### Commands

```
  6x -2:54.4.0 core:move-up (input.hidden-input)
     -2:52.9.0 core:move-down (input.hidden-input)
  2x -2:52.1.0 editor:newline (input.hidden-input)
  2x -2:50.9.0 core:move-up (input.hidden-input)
     -2:47 core:move-down (input.hidden-input)
     -2:46.7.0 core:move-right (input.hidden-input)
     -2:46.4.0 core:move-left (input.hidden-input)
     -2:45.6.0 core:backspace (input.hidden-input)
     -2:44.6.0 core:move-up (input.hidden-input)
  2x -2:43.9.0 core:move-down (input.hidden-input)
  2x -2:43.4.0 core:move-up (input.hidden-input)
     -2:38.2.0 editor:newline (input.hidden-input)
     -2:37.2.0 core:move-up (input.hidden-input)
  2x -2:31.6.0 core:backspace (input.hidden-input)
     -2:30.2.0 core:save (input.hidden-input)
     -2:07.5.0 core:save-as (input.hidden-input)
```

### Non-Core Packages

```
atom-xterm 6.5.0 
gpp-compiler 3.0.7 
ide-python 1.4.1 
python-tools 0.6.9 
run-python-simply 0.6.0 
teletype 0.13.3 
```

**Comment by UziTech** [comment]
I forked `atom-xterm`, updated everything along with other fixes, and released it as [`x-terminal`](https://atom.io/packages/x-terminal) since `atom-xterm` doesn't seem to be maintained
