### ISSUE TITLE
Failed to activate the atom-xterm package

### ISSUE THREAD

**Issue by aman-kumar-jh** [amejia1/atom-xterm#77]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.39.1 x64
**Electron**: 3.1.10
**OS**: Ubuntu 18.04.2
**Thrown From**: [atom-xterm](https://github.com/amejia1/atom-xterm) package 6.5.0

### Stack Trace

Failed to activate the atom-xterm package

```
At Cannot find module '../build/Release/pty.node'

Error: Cannot find module '../build/Release/pty.node'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Module._resolveFilename (/snap/atom/235/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/snap/atom/235/usr/share/atom/resources/app/static/<embedded>:11:155394)
    at Module.require (/app.asar/static/index.js:60:43)
    at require (/snap/atom/235/usr/share/atom/resources/app/static/<embedded>:11:146719)
    at /packages/atom-xterm/node_modules/node-pty-prebuilt/lib/unixTerminal.js:22:11)
    at /packages/atom-xterm/node_modules/node-pty-prebuilt/lib/unixTerminal.js:266:3)
    at Module.get_Module._compile (/snap/atom/235/usr/share/atom/resources/app/static/<embedded>:11:147410)
    at Object.value [as .js] (/snap/atom/235/usr/share/atom/resources/app/static/<embedded>:11:150958)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:71:46)
    at require (/snap/atom/235/usr/share/atom/resources/app/static/<embedded>:11:146719)
    at /packages/atom-xterm/node_modules/node-pty-prebuilt/lib/index.js:13:20)
    at /packages/atom-xterm/node_modules/node-pty-prebuilt/lib/index.js:50:3)
    at Module.get_Module._compile (/snap/atom/235/usr/share/atom/resources/app/static/<embedded>:11:147410)
    at Object.value [as .js] (/snap/atom/235/usr/share/atom/resources/app/static/<embedded>:11:150958)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:71:46)
    at require (/snap/atom/235/usr/share/atom/resources/app/static/<embedded>:11:146719)
    at /packages/atom-xterm/lib/atom-xterm-element.js:20:43)
    at /packages/atom-xterm/lib/atom-xterm-element.js:583:19)
    at Module.get_Module._compile (/snap/atom/235/usr/share/atom/resources/app/static/<embedded>:11:147410)
    at Object.value [as .js] (/snap/atom/235/usr/share/atom/resources/app/static/<embedded>:11:150958)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
```

### Commands

```
```

### Non-Core Packages

```
atom-xterm 6.5.0 
gpp-compiler 3.0.7 
```

**Comment by UziTech** [comment]
I forked `atom-xterm`, updated everything along with other fixes, and released it as [`x-terminal`](https://atom.io/packages/x-terminal) since `atom-xterm` doesn't seem to be maintained
