### ISSUE TITLE
Uncaught Error: /snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found...

### ISSUE THREAD

**Issue by VoidIsEverywhere** [amejia1/atom-xterm#88]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Ubuntu 19.10
**Thrown From**: [atom-xterm](https://github.com/amejia1/atom-xterm) package 6.5.0

### Stack Trace

Uncaught Error: /snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/void/.atom/packages/atom-xterm/node_modules/node-pty-prebuilt/build/Release/pty.node)

```
At ELECTRON_ASAR.js:160

Error: /snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/void/.atom/packages/atom-xterm/node_modules/node-pty-prebuilt/build/Release/pty.node)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:160:31)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/snap/atom/248/usr/share/atom/resources/app/static/<embedded>:11:146745)
    at /packages/atom-xterm/node_modules/node-pty-prebuilt/lib/unixTerminal.js:22:11)
    at /packages/atom-xterm/node_modules/node-pty-prebuilt/lib/unixTerminal.js:266:3)
    at Module.get_Module._compile (/snap/atom/248/usr/share/atom/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/snap/atom/248/usr/share/atom/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/snap/atom/248/usr/share/atom/resources/app/static/<embedded>:11:146745)
    at /packages/atom-xterm/node_modules/node-pty-prebuilt/lib/index.js:13:20)
    at /packages/atom-xterm/node_modules/node-pty-prebuilt/lib/index.js:50:3)
    at Module.get_Module._compile (/snap/atom/248/usr/share/atom/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/snap/atom/248/usr/share/atom/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/snap/atom/248/usr/share/atom/resources/app/static/<embedded>:11:146745)
    at /packages/atom-xterm/lib/atom-xterm-element.js:20:43)
    at /packages/atom-xterm/lib/atom-xterm-element.js:583:19)
    at Module.get_Module._compile (/snap/atom/248/usr/share/atom/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/snap/atom/248/usr/share/atom/resources/app/static/<embedded>:11:150977)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-clock 0.1.17 
atom-ide-debugger-python 0.7.3 
atom-ide-ui 0.13.0 
atom-xterm 6.5.0 
busy-signal 2.0.1 
file-icons 2.1.39 
framer-syntax 1.1.0 
framer-ui 2.0.0 
git-control 0.9.0 
git-plus 8.7.1 
git-time-machine 2.1.0 
highlight-selected 0.17.0 
ide-html 0.6.0 
ide-python 1.5.0 
intentions 1.1.5 
linter 2.3.1 
linter-ui-default 1.8.1 
minimap 4.29.9 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-hide 0.3.0 
minimap-highlight-selected 4.6.1 
minimap-linter 2.2.1 
minimap-pigments 0.2.2 
minimap-selection 4.5.0 
pigments 0.40.2 
python-debugger 0.2.0 
run-in-terminal 1.0.1 
script 3.25.0 
script-runner 2.5.0 
seti-ui 1.11.0 
teletype 0.13.4 
```

**Comment by UziTech** [comment]
atom-xterm is no longer maintained [x-terminal](https://atom.io/packages/x-terminal) is an updated and maintained version of atom-xterm.
